# Applications

Some _significant_ applications are demonstrated in this chapter.

## Example one

## Example two



Time series of repeatedly measured human performances presents fluctuations around a mean value. These fluctuations are typically considered as insignificant, and attributable to random noise. Over recent decades, it has become increasingly clear that fluctuations in repetitive performance possess interesting properties, however, one of which the property of 1/f, or monofractal, scaling. 1/f scaling indicates that a measured process extends over a wide range of timescales, suggesting that the measured process is assembled over all of these scales simultaneously. The present paper reviews a substantial number of neurological, physiological, and cognitive studies that corroborate the claim that 1/f scaling is most clearly present in healthy, well-coordinated activities. The most prominent hypotheses about the origins of 1/f scaling in human activities are confronted in light of these reviewed studies. A synthesis of this confrontation points towards the conjecture that 1/f scaling in living systems reflects the genuine complex nature of cognitive systems, and casts doubt over claims that 1/f scaling is a coincidental side-effect of information processing sequenced through discrete neurological modules. The consequences of fractal dynamics extending over brain, body and cognition, from the small spatial and temporal scales (e.g., neurons) to the larger scales of human behavior and  cognition, are vast, and impact the way in which relevant research questions should be approached. Rather than focusing on specialized isolable subsystems, using additive linear methodologies that specifically aim at doing so, nonlinear dynamics, more elegantly so, imply the more appropriate complex systems methodology, thereby exploiting, rather than rejecting, mathematical concepts that describe large sets of natural phenomena.


The presence of 1/f scaling in human performances is arguably one of the most puzzling, yet lawful phenomena in cognitive science. (see Diniz et al., 2010; Gilden, 2001; Van Orden, Holden & Turvey, 2003; 2005, Riley & Turvey, 2002; Slifkin & Newell, 1998; Wagenmakers, Farrell, & Ratcliff, 2005). 1/f scaling represents fractal, self-similar processes nested across multiple scales of measurement. Its occurrence implies that the rescaling of a time series leaves the distributional properties of the time series unaffected. Intriguingly from both a statistical and theoretical point of view, fractal scaling is widespread across the central nervous system, motor behavior, cognitive performances, and well beyond. As will be discussed, many physical and physiological signals exhibit scale-invariant features. Because it is now well-known that the presence of 1/f scaling has a profound impact on cognitive and physiological activities, the phenomenon warrants serious attention.

Despite the fact that 1/f scaling is a mathematical concept that allows for descriptions of large sets of natural phenomena, the study of this relatively simple lawful description is relatively new. 1/f scaling, nonetheless, has the potential to reveal unexpected congruities among neurological, physiological and cognitive activities A general back draw is that the observation of 1/f scaling in itself runs against standard statistical intuitions. That is, successive observations of a repeated behaviors are typically assumed to represent measurement values that are independently drawn from a Gaussian distribution, and thus to fluctuate randomly from trial-to-trial. Over recent decades, however, it has become clear that movement variability rarely equates with random, Gaussian noise, and that temporal variability is usually structured and reveals specific details of the system dynamics (Gilden, 2001; Riley & Turvey, 2002; Slifkin & Newell, 1998; Stergiou & Decker, 2011; Torre & Balasubramaniam, 2011). 

In fact, structured variability appears to be the rule rather than the exception, and is often as revealing as aggregate information in terms of unpacking the nature of the system organization (Ihlen & Vereijken, 2010; Kello, Beltz, Holden, & Van Orden, 2007; Van Orden et al., 2003). 

1/f scaling implies long-range dependence in the signal, often called long-range correlations or long memory. The associated serial correlations from trial to trial decay very slowly as the number of intervening trials increases, indicating persistent serial correlations, in contrast with the traditional view that they are transient (see e.g., Gilden, 2001). This sets 1/f scaling apart from random noise, which lacks this serial dependence.

One way of revealing 1/f scaling is by translating dependencies in the time domain (i.e., a pattern of change in response time over trials) as simple features in the frequency domain using an operation called a Fourier transform, which decomposes the data series containing changes in response over trials into its constituent frequencies. Next, the power (the square of the amplitude) of each contributing wave at that frequency in the decomposed signal is plotted in a log-log power spectrum. Also called power spectral density function, such a log-log power spectrum for a random data series (white noise, see Figure 1a) is shown in Figure 1b. 

White noise is not long-range correlated, as represented by a flat slope in a log-log power spectrum. 1/f scaling, in contrast, expresses as an inversely proportional relation between log power and log frequency (see Figure 1d). This implies a nested sequence effect spanning over the entire time course of a measurement and even beyond, encompassing undulating “waves” of relatively longer and then shorter response times travelling across the series. Specifically, faster (high-frequent) changes in response time are typically small, and embedded in overarching, slower (lower-frequent) changes of higher amplitude (see Figure 1c). A third class of variability is Brownian noise (see Figure 1e), which can be generated by adding  successive observations generated by a white noise process. Brownian noise is nonstationary, which means that variance increases over time. The log-log power spectrum of Brownian noise has a slope of -2 (see Figure 1f).

 
Figure 1. Three different classes of temporal variability, white noise (a), 1/f scaling (c), and Brownian noise (e), and their respective power spectra are shown in the respective panels at the right.

Typically, repeated human behaviors show a scaling exponent α in the range of 0 and 1, in between random noise and 1/f scaling. Examples of cognitive tasks include mental rotation, lexical decision, and visual search (Gilden, 2001), simple reaction time and word-naming (Van Orden et al., 2003), forearm oscillation (Delignières, Torre, & Lemoine, 2008), synchronization to a metronome (Chen, Ding, & Kelso, 1997); implicit associations (Correll, 2008), bi-daily reports of self-esteem (Delignières, Fortes, & Ninot, 2004), and movement times in an aiming task (Valdez & Amazeen, 2008; Wijnants et al., 2009), among others. But sometimes α varies between 1 and 2 or even beyond, often in continuous processes like postural sway (e.g., Collins & De Luca, 1993), force production (Sosnoff, Valantine, & Newell, 2009), or galvanic skin response (Wijnants, Cox, Hasselman, Bosman, & Van Orden, 2012).

The aim of this paper is to review the fascinating linkage between 1/f scaling and healthy, well-coordinated activities. Next, the most pertinent hypotheses about the origins of 1/f scaling in human activities are discussed, followed by a critical assessment  of their relative strengths and weaknesses. Any of these hypotheses are able to successfully explain the presence of 1/f scaling, but postulate opposing  underlying mechanisms. The proposal put forwards is that questions concerning potential mechanisms and models that produce 1/f scaling should be rephrased. What matters is which explanation accounts best for the general linkage between observed fractal dynamics and coordinated physiological and cognitive processes. After all, each distinct accounts will have to deal with this broad linkage.


2.	Fractal dynamics and system coordination
Recent years have witnessed increasing empirical support for widespread 1/f scaling in time series of physiological and behavioral processes. A main theme of this review focuses specifically on the association of 1/f scaling with healthy and well-coordinated behaviors.  That is, deviations from 1/f scaling are often related to pathologic disorders, aging, external perturbations, high workload, or other situations where the system was not fully functional or coordinated. Rather than an incidental finding, this relation appears to be global, and extends from small spatial and temporal scales (e.g., neurons) to the larger scale of human behavior itself. 

That said, the growing body of research has further complicated this picture, showing that changes in the scaling relation occur simultaneously, and sometimes independently, on shorter (i.e., sleep-wake cycles, rest versus exercise, or circadian phases) and longer time scales, such as learning or aging (e.g. Ivanov et al., 1999; Hu et al., 2004; Kantelhardt, 2002; Karasik et al., 2002; Schumann, Bartsch, Penzel, Ivanov, & Kantelhardt, 2010). Observing deviations from 1/f scaling in shorter scale processes (e.g., transitions from one physiological state to another) under young and healthy conditions invite for a critical review. of the relation between system performance and the presence of 1/f scaling on the longer behavioral scales, to a) evaluate whether the current state of knowledge allows arriving at a coherent theoretical framework, and b) pinpoint the questions that remain to be answered.
 
One biological example that hints at the generality of the claimed relation between coordinated system behavior and 1/f scaling are the vibratory motions of the membrane of red blood cells. The human body continuously produces new red blood cells (approx 2.4 million a second, cf. Sackmann, 1995), which compose a third of the cells in the human body (Pierigè, Serafini, Possi, & Magnani, 2008). Red blood cells are renewed after approximately 120 days, however. Interestingly, the membrane of red blood cells spontaneously vibrates, or ‘flickers’, revealing 1/f scaling. Costa, Ghiran, Peng, Nicholson-Weller, and Goldberger (2008) in addition that the dynamical properties of this flickering behavior change with in vivo aging. Older cells emit less clear 1/f scaling, compared with newer cells that carry more oxygen.

This example is meaningful, since red blood cells constitute an important, basic system component, which is strongly related to an adequate functioning of one’s physiology (and, hence, by extension human behavior). By reviewing functional benefits of fractal dynamics for living systems, an attempt is made to offer a vehicle for theoretical progress on the topic of 1/f scaling in cognitive performances. The steadily growing body of reliable positive evidence contradicts and grossly surprises conventional thinking about the architecture of cognitive systems. For one, a common scale-free ‘language’ among perceptual-motor or cognitive tasks and (neuro-)physiology are not expected from classical componential models, which typically posit domain-specific control structures. 

2.1.	 Pervasive fractal scaling in the central nervous system 
Brain activity is being investigated across a multitude of  embedded scales of analysis. The finest level is the molecular scale which makes up cells, neurotransmitters etc. Courser levels of brain activity include cell membranes with their synapses, microcircuits of dentritic trees, whole neurons, local cortical circuits consisting out of nearby neurons, entire cortical regions, and interactions among cortical regions and pathways connecting them. At the coarsest scale one finds the central nervous system as a whole, embedded in a body, history, and environment . Evidence of fractal scaling at all of these levels would suggest common dynamical constraints across these embedded scales of organization, begging the question whether the presence of fractal scaling provides support to this multiscale organization.

Anatomically out first, a mammalian brain reveals fractal properties in branching dendrite patterns, thereby maximizing functionality for a fixed dendrite cost (Bassingthwaighte, Liebovitch, & West, 1994; Kniffki, Pawlak, & Vahle-Hinz, 1994; Smith, Marks, Lange, Sheriff, & Neale, 1989), suggesting that fractal scaling in morphological specializations at the cellular level has a functional role (see also Harrison et al., 2002; Milosevic, Ristanovic, Stankovic, & Gudovic, 2007; Zietsch & Elston, 2005). As a different example, fractal characteristics of microglia differentiate between healthy and pathological brains (Karperien & Jelinek, 2008; Soltys, Ziaja, Pawlinski, Setkowicz, & Janeczko, 2001). And, also at more global organizational levels of the brain, fractal morphology yields functional advantages (Ha et al., 2005, Zhang, 2006).

The spatial fractal structure of brain anatomy aside, temporal dynamics are remiscent of complex behavior across many scales just as well: 1/f power-law scaling in temporal activation patterns has been observed at all levels of neural organization, from ion channels opening and closing times to cortical networks (Werner, 2010). The question of primary interest is how the dynamics of ion channels (Liebovitch & Krekora, 2002; Liebovitch & Shehadeh, 2005; Lowen , Cash, Poo, & Teich, 1997; Takeda, Sakata, & Matsuoka, 1999, Varanda, Liebovitch, Figueiroa, & Nogueira, 2000) interact with, rather than concatenate to, fractal spike intervals (Bhattacharya, Edwards, Mamelak, & Schuman, 2005; Giugliano, Darbon, Arsiero, Luescher, & Streit, 2004; Grüneis et al., 1993, West & Deering, 1994), and the functional characteristics of larger scale neural ensemblies (Buzsàki, 2006; Bressler & Kelso, 2001; Freeman, Holmes, Burke, & Vanhatalo, 2003; Spasic, Kesic, Kalauzi, & Saponjic, 2010; Tognoli & Kelso, 2009; Varela, Lachaux, Rodriguez, & Martinerie, 2001; Werner, 2007). 

Important clues may come from pathological brains. For instance, deviations from 1/f scaling, as typically observed in healthy controls,  have been found with major-depressive disorder (Linkenkaer-Hansen et al., 2005), mania (Bahrami, Seyedsadjadi, Babadi, & Noroozian, 2005), autism (Lai et al., 2010), epilepsy (Ramon, Holmes, Freeman, McElroy, & Rezyanian, 2008), and Alzheimer’s disease (Abásolo, Hornero, Gómez, García, & López, 2008). These results suggest that 1/f scaling is prevalent in healthy, coordinative behavior of a healthy brain, and less so in the global activity of the brain with disorders and disease. Following on this suggestion, it was shown that the presence of 1/f scaling in brain activation correlates with the severity of depression symptoms (Linkenkaer-Hansen et al., 2005) and the success rate of recovery from traumatic brain injury (Burr, Kirkness, & Mitchell, 2008).

The scale complexity inherent to the study of brain activity makes it an enormous challenge for neuroscience to arrive at a universal theory of brain function. One first complication comes from the requirement of different methods at each level or scale of neural investigation. Each of the methods available yields a compromise between spatial and temporal resolution and, consequently, yields a priori choices in the organizational level of interest. No current method in isolation is likely capable of revealing the full-blown complexity of the brain, from the decimeter to the micrometer scale and from milliseconds to minutes up to developmental timescales. The discussed findings, however, should be taken as a strong suggestion that the inherent scale complexity of the human brain is a (if not the) key feature in itself. 

2.2.	 Pervasive fractal scaling in the body
A substantial amount of fractal applications in cognitive research have been motivated by initial successes in physiology, which had related 1/f scaling to the coordination, adaptivity and flexible stability of the involved regulatory processes. Deviations from 1/f scaling in physiology have been found to relate to the degradation and decoupling of integrated systems, pathological conditions, severe disease and increased mortality risk. 

For instance, heartbeat interval series show 1/f scaling, with the clearest examples in healthy subjects. Deviations from 1/f scaling, either associated with excessive order (pathologic periodicity), or uncorrelated white noise (lack of temporal organization), indicate pathological conditions like congestive heart failure and ventricular arrhythmia (Goldberger, 1997; Peng et al., 1995), and thus predict mortality (Mäkikallio et al., 2001). Smaller deviations from 1/f scaling have been observed in heartbeat intervals in obese children (Vanderlei, Pastre, Júnior, & de Godoy, 2010) and adults with Down Syndrome (Mendonca, Pereira, & Fernhall, 2011). 

However, although alterations in the fractal properties of physiologic signals have been found to be reliable markers of changes in physiologic control, with healthy aging scale-invariant and nonlinear properties of heartbeat dynamics remain unchanged, with heart rate variability is significantly reduced healthy elderly, nonetheless (Schmitt & Ivanov, 2007; Schmitt, Stein, & Ivanov, 2009). These findings suggest that healthy aging may not result in a continuous gradual change in scaling properties of heartbeat intervals, and implies that alterations in the cardiac control mechanism with advanced age differ conceptually from the mechanistic changes in the autonomic regulation associated with pathologic conditions.

Also breathing rhythm reveals 1/f scaling behavior, but shows deviations thereof with aging (Peng et al., 2002; West, 2006). The contrary goes for development. Fetal breathing movements show more pronounced 1/f scaling with gestational age (Govindan, Wilson, Murphy, Russel, & Lowery, 2007). In contrast, deviations from 1/f scaling are observed in asthma patients, out of which those with more pronounced 1/f signatures in breathing rhythm showed better recovery after treatment (Frey et al., 2005). These findings indicate together that fractal dynamics increase the overall efficiency of the respiratory system (cf. West, 2010). 

Also fluctuations in blood pressure are found to scale as 1/f (Mutch et al., 2000, Brogan et al., 2007). Diabetic patients, however, show reduced 1/f noise specifically in glucose fluctuations compared with healthy controls (Ogata et al., 2007; Yamamoto et al., 2010). Other examples include by fluctuations in colonic pressure. Yan, Yan, Zhang & Wang (2008) observed 1/f fluctuations in the colonic activity of the healthy subjects, while patients hospitalized for slow transit constipation showed colon pressure fluctuations deviating from 1/f noise towards Brownian noise; a condition yielding hardly bearable levels of pain sensation. 

In physiology and medicine it is being increasingly acknowledged that a disease not only changes an average measure, such as heart rate or breathing rate, but is manifest in departures from fractal variability. Deviations from 1/f scaling are taken to imply a loss of physiologic control, which is often visible at very early stages of pathological development. The change in fractal dynamics with disease and, in some cases, aging suggested the new definition of disease as a loss of complexity, rather than the loss of regularity (e.g., Goldberger et al, 2002). 

2.3.	Pervasive fractal scaling in motor control
As in neuroscience, medicine, and physiology, there has been an increasing interest in fractal dynamics in human movement science. For instance, time series of postural sway differ reliably from random noise, revealing fractal properties (e.g., Duarte & Sternad, 2008; Duarte & Zatsiorsky, 2001; Collins & De Luca, 1993). Moreover, the clearest examples of 1/f scaling are found in young participants, while elderly participants show less clear fractal scaling in their postural dynamics (Doyle, Dugan, Humphries, & Newton, 2004), indicating degraded balance control (Collins & De Luca, 1995; Laughton et al., 2003; Maurer, Mergner, & Peterka, 2004; Priplata, Niemi, Harry, Lipsitz, & Collins, 2003; Priplata et al., 2006). This interpretation was further supported by Manabe et al. (2001), who demonstrated less clear 1/f scaling in postural sway dynamics for patients suffering from Parkinson’s disease and spinocerebellar ataxia, when compared to a control group. Interestingly, fractal measures of postural sway were even found more reliable than more traditional measures (Doyle, Newton, & Burnett, 2005).

Also in gait intervals (Hausdorff, 2007; 2009, are reviews), - the time intervals between successive steps in locomotion -, the clearest examples of 1/f scaling are observed in young and healthy participants, whereas with aging, gait interval series become more random. It must be noted, however, that, while cardiac and respiratory dynamics show a more pronounced 1/f scaling and also higher degree of nonlinearity with gestation age and maturation, locomotion exhibits deviations from 1/f scaling towards more random scaling are observed as early as maturation from childhood to adulthood (cf. Ashkenazy, Hausdorff, Ivanov, Goldberger, & Stanley, 2008; Hausdorff et al., 2001). 

In an elderly population, however, the presence of 1/f scaling successfully discriminates between fallers from non-fallers, and between Huntington’s patients and control participants (Hausdorff, 2007). Moreover, the fractal dynamics of stride intervals produced by Huntington’s patients correlates strongly with the severity of the illness (r = -.78, cf. Hausdorff, 2007), suggesting that deviations from 1/f scaling suggest impaired control of locomotion. Hausdorff (2009) describes similar findings in Parkinson’s disease patients, and observed that among patients Parkinson’s disease, the 1/f scaling relation in gait intervals “breaks down” and the stride-to-stride fluctuation in gait becomes very similar to white noise; each stride starts a new process, unlinked and unrelated to the previous stride. After successful treatment with proper medication, however, 1/f scaling becomes more prominent again in Parkinson patients’ gait dynamics (Auriel, Hausdorff, Herman, Simon, & Giladi, 2006). 
 
Using a different motor task, Wijnants, Bosman, Hasselman, Cox, and Van Orden (2009) presented college students with a very challenging precision-aiming (i.e., Fitts) task. The instruction was to move as fast and as accurately as possible between two circular targets with an inkless stylus. Participants were presented with five training blocks of 1100 back-and-forth movements. Very small targets were used, positioned wide apart, while participants were instructed to use their non-dominant, least-practiced hand. A learning effect was observed after the extensive number of practice trials. Participants reached the narrow targets much faster after practice, while accuracy was maintained. A reliable effect of practice was found in the presence of 1/f scaling in movement time fluctuations; the presence of 1/f scaling became more pronounced with motor learning.

In a later study, Wijnants, Cox, Hasselman, Bosman, and Van Orden (2012) examined 1/f scaling in both spatial (movement amplitude) and temporal (movement time) time series in the challenging precision-aiming task, so notorious for revealing speed-accuracy trade-off (cf. Fitts, 1954). Because of the difficulty of the task, participants were required to either emphasize the speed or the accuracy side of the trade-off (while equally being instructed to move as fast and as accurately as possible between targets) simply because the dual task constraints were so incompatible. The emphasized task requirement (temporal or spatial) directly affected the presence of 1/f scaling. Faster participants produced clearer 1/f scaling in movement times, but more random dynamics in movement amplitudes, as they performed the task less accurately. Conversely, more accurate participants produced more random dynamics in movement time sequences, as they performed the task more slowly, and clearer 1/f scaling in movement amplitude series. This effectively led to a trade-off between spatial and temporal 1/f scaling (ρ = −0.64), contingent on the so well-established speed-accuracy trade-off.

In the same study, Wijnants et al. (2012) established a strong relation between the fractal dynamics of movement time vs. movement amplitude and the biomechanical constraint of minimizing the dissipation of mechanical energy. Faster participants, who produced clearer 1/f scaling in their movement time series also better capitalized on the elastic properties of the muscular system to recycle the kinetic energy of the approaching hand, arm, and shoulder in potential form, which is energetically to the benefit of the next movement. Together, this amounted to a strong coupling among measurement scales in human performance: the biomechanical details emerged within the timeframe of a single movement, while speed and accuracy are determined by entire movements. The third timescale included the fractal dynamics that extend up to minutes of performance. The strong coupling between these multiple levels of motor performance provided further exquisite support for the nested multi-scale properties in the organization of the cognitive system.

In contrast, externally driven performances have been found to minimize intrinsic fractal fluctuations. For instance, Chen, Ding, and Kelso (1997) observed no 1/f scaling when tapping to a metronome (1/f scaling was observed in the asynchronies to the metronome, nonetheless), while 1/f scaling is clearly present in self-paced inter-tap intervals (cf. Gilden et al., 1995). Similarly, in consecutive gait-cycles the external drive of a metronome breaks down the long-time correlations of the natural pace and generates random variability (Hausdorff, 2007).

In a bimanual force production task, Wing, Daffertshofer, and Pressing (2004) observed random or close to random variability when feedback was presented to the participants (another form of external drive), while much clearer 1/f scaling was observed when no feedback was provided. Kello et al. (2007) and Van Orden et al. (2003) interpreted these findings, altogether, as a confirmation that feedback provided constitutes a type of external perturbation that de-correlates the intrinsic fluctuations of 1/f scaling. 

Perhaps the epitome of exercising external perturbation to motor control is to add a cognitive task on top of an initially simple motor task.  Dual-tasking paradigm has been found to induce reduced 1/f scaling in the primary motor task (Kiefer, Riley, Shockley, Villard, & Van Orden, 2009). This finding was replicated in a different task by Hausdorff (2009); who Parkinson’s patients to walk while performing a challenging secondary task. The gait dynamics revealed a reduced presence of 1/f scaling, compared with a no dual-tasking condition.

2.4.	 Pervasive fractal scaling in human cognition
The presented results from neuroscience, physiology, and movement science, naturally extend to cognitive performances. Consider Figure 2, which depicts the average 1/f scaling exponents observed in four different experiments; word naming (Van Orden et al., 2003), choice reaction (Kello et al., 2007), simple reaction (Van Orden et al., 2003), and precision aiming (Wijnants et al., 2009). It is clear that the presence of 1/f scaling gradually increases over these tasks. Note that in precision aiming and simple reaction tasks, each experimental trial is identical. Each trial yields the same stimuli and the same type of response. This means that external sources of variation are minimized in these task performances. Consequently, the observed variation must largely reflect internal sources, which can be seen as a clearer presence of 1/f scaling in those tasks. One can readily notice the difference between precision aiming and simple reaction times. Precision aiming is a cyclic task, while simple reaction times become perturbed by a discrete signal to respond at each trial, and requires a discrete response at each trial. It can be seen that the extent of this perturbation effectively leads to a reduced presence of 1/f scaling. 

The other end of the scale shows the 1/f scaling exponents from a word-naming task and a choice reaction task. In these tasks, each experimental trial differs, but to a different extent. In the choice reaction task, four different signals to respond were presented, with each signal requiring a different response. This procedure introduces more external sources of variation, which is revealed by a more whitened 1/f signal. Word-naming reveals the most reduced example, a task in which every experimental trial introduces a unique signal to respond. Hence, external sources of variation are maximized in this procedure, and the measured values likely reflect the intrinsic sources of variation to a lesser extent, requiring a more flexible and adaptive, perhaps less organized, control strategy. Similarly, the presence of 1/f scaling is typically reduced under high workload conditions (Clayton & Frey, 1997; Correll, 2008; 2011) and when a sequence of presented stimuli becomes less predictable (Kello et al., 2007).

 
Figure 2. The fractal scaling exponents from four independent experiments are shown. It is shown that 1/f scaling become more clearly present as the number of different response options decreases (see text). The shown tasks include word-naming, choice reaction, simple reaction, and precision aiming.

A closer look at one of the tasks, choice reaction, reveals a similarly interesting finding. Ward (2002) discusses an experiment that was set up to manipulate the number of stimulus and response alternatives. In that study, Ward and Richard (2001) presented participants with a choice reaction task that consisted out of either one (simple reaction), two, or four stimulus-response alternatives. The authors effectively showed that the presence of 1/f scaling is reduced as the number of stimulus-response alternatives increased. The scaling exponents were .60 for the simple reaction task, .37 for the two- choice reaction task, and .24 for the four-choice reaction task ..

Another example of systematic perturbations attenuating the presence of fractal dynamics comes from Kuznetsov and Wallot (2011), who presented participants with a temporal estimation task, in either of five conditions of accuracy feedback. In one condition, feedback was provided at every estimate, in another condition no feedback was given at all. In the remaining conditions, feedback was displayed only if the temporal estimate deviated from the target interval by more than 50, 100, or 200 ms respectively. The results revealed an increase of 1/f scaling in conditions where less feedback (i.e., intermittent sources of perturbation) was provided, and hence, where the intrinsic cognitive fluctuations were revealed most clearly. 

Gilden and Hancock (2007) compared the performance of adults who reported Attention Deficit Hyperactivity Disorder (ADHD) symptoms with a control group of adults who did not, in a mental rotation task. The instruction was to press a key if the stimulus (a letter rotated by 0, 60, 120, 180, 240, or 300 degrees) was mirror-inverted, and another key if the stimulus was not. Distinctive dynamical patterns of response in the reaction times were observed in both groups. More consistent participants revealed fractal scaling exponents close to 1/f scaling, while the more variably performers revealed random walk dynamics with a spectral slope close to -2. Hence, the more efficient system responses yielded a relatively clear 1/f signal, while the less coordinated, attention-deficit responses deviated from that pattern.

Wijnants, Hasselman, Bosman, Cox, & Van Orden (2012) inquired fractal scaling properties in the context of another learning disability. Response latencies of young children diagnosed with developmental dyslexia were compared with response latencies of non-dyslexic children. The authors revealed that 1/f scaling measures reliably differentiated between both groups of readers when reading aloud single words sequentially. The dyslexic readers revealed more random response times, while average readers revealed clearer 1/f scaling. Furthermore, in the dyslexic group the 1/f scaling exponents of the response time series strongly correlated with the severity of the reading impairment, as determined by average response time (r = -0.56, the negative correlation indicates that slower responses were associated with less clear 1/f scaling) and standardized reading scores (r = 0.77, the positive correlation indicates that lower reading scores are associated with less clear 1/f scaling).

The summarized findings from research incorporating behavioral responses to repeated stimuli are very similar to the findings in neuroscience, physiology and movement science. These findings raise the suggestion that many measurements related to how humans respond to repeated stimuli reveal signatures of complexity akin to the scaling behavior observed in simultaneously occurring processes (e.g., in the brain and the body). Importantly, these ‘cognitive’ processes are traditionally treated as independent and self-supporting ‘directive systems’ (i.e., the brain modules ‘in charge’) or ‘executive systems’ (i.e., the autonomous nervous system ‘doing what it is directed to do’). The very observation that they may not be independent and self-supporting, but rather massively interactive, – and complex in a true complex systems sense- , could however, cast doubt on the validity of the common sense distinction between the directive and executive front seemingly involved in the coordination of human action (Van Orden, Hollis, & Wallot, 2012; Varela et al. 2001).

3. Theoretical perspectives on 1/f scaling in human performance
1/f scaling relations are systematically manipulable, and indicate adaptive and flexible performances where no single timescale dominates coordination. Cognitive systems thus appear to ongoingly maintain a balance between competitive and cooperative processes in a flexible coupling across brain, body and cognition. By confronting the most prominent, yet competing, hypotheses with the empirical observations presented above, an attempt is made towards a single conclusive theoretical account.

3.1.	Multi-scaled randomness 
One account for widespread 1/f scaling in human cognition conceives the phenomenon as reflecting many independent processes, each acting individually on their own timescale (e.g., Granger, 1980; Hausdorff & Peng, 1996; Pressing, 1999; Wagenmakers, Farell, & Ratcliff, 2004; Ward, 2002; Wing et al., 2004). For example, consider a time series where each measured response X constitutes the sum of three different processes Y1, Y2  and Y3, each evolving at their own independent timescale, in the additive form; X(t) = Y1(t) + Y2(t) + Y3(t). If one then assumes that Y1 is a quickly random changing process, Y2 is a random intermediate process, and Y3 is a slowly randomly changing process, the additive series of all Y’s may yield 1/f scaling under specific circumstances (see for instance, Hausdorff & Peng, 1996; Wagenmakers et al., 2004). 

Figure 3 shows schematically a power spectrum from repeated responses that combine the activity of a multitude of independent processes, each at their own timescale. In this schematic representation, indeed, the schematic distributions of time scales lead to 1/f behavior (see e.g. Beran, 1994, for a more detailed description). This suggests that the complex fluctuations and 1/f scaling observed in many biological systems do not convey anything ‘special' about the mechanism generating these dynamics. From this perspective, 1/f scaling is a rather coincidental event that reflects nothing more than an artifact of information processing.

 
Figure 3. A schematic representation of the multi-scaled randomness construct. The left panel shows five hypothesized processes, each evolving at their own timescale. A time series composed of the sum of these processes may reveal 1/f-like noise in a power spectrum, which is shown in the right panel. Note that the processes are depicted schematically, and may compose random processes with differing relaxation times, rather than deterministic sine waves.


The main benefit of explaining 1/f scaling by aggregation of component processes is that such an explanation is conceptually simple and seemingly transparent, and may therefore ‘demystify’ the widespread occurrence of 1/f scaling (cf. Wagenmakers et al., 2004). That is, a componential model, consisting of many independent components, is effectively able to produce transient short-range correlations that, together, by chance may closely mimic the 1/f scaling behavior that is so ubiquitously observed across neurology, physiology, motor behavior, and cognition (e.g., Hausdorff & Peng, 1996; Pressing, 1999; Wagenmakers et al., 2004; 2005). 

Consider for instance the often cited dice-throwing algorithm in Gardner (1978). When from three dice, the first is thrown only rarely, the second intermittently, and the third at every observation. The sum of the values, when taken over a range of observations, will fluctuate in a 1/f-like fashion, under specifically constrained conditions.

Nonetheless, there are a number of drawbacks. For one, independent multi-scaled processes must exactly match the power and frequency associated with each involved component in order to coincide with a 1/f scaling pattern. However, if all parameters of the model are free, it is very unlikely that a system would, by chance, choose the ``proper'' parameters necessary to consistently generate 1/f-like noise, let alone accumulate consistent relative changes across so many manipulations in neuroscience, physiology, and cognitive science. That is,  “simulations demonstrate that if model parameters are unconstrained, the likelihood of generating 1/f noise is quite small. Thus, while the model can be used to generate 1/f noise with various scaling exponents, it is unlikely that the 1/f behavior observed in many biological systems is due only to the fact that these systems are regulated by many different inputs acting on different time scales.” (Hausdorff & Peng, 1996, p. 2154). 

A second important drawback from multi-scaled randomness is the lack of parsimony in the model. For every independent 1/f signal observed new components need to be asserted (Kello et al., 2007; Kello, Anderson, Holden, & Van Orden, 2008; Van Orden et al., 2003; 2005). If not, that would mean the components are shared between processes, meaning each component is notstrictly interdependent. Components of perception and action would hinge on synergies of physiological and cognitive component activities. 

If one, in addition, considers a non-generic 1/f process measured over a time range of ten minutes, or twenty minutes, regardless of its nature, multi-scaled randomness woul imply scaling relations to bend off at the lowest frequencies in the log-log power spectrum when sampling extends over longer periods of time (e.g. Pressing & Jolley-Rogers, 1997). In the counter case, infinitely more short-range processes are to be invoked to keep the spectrum from flattening at the low frequencies (e.g. Torre & Wagenmakers, 2009; see Van Orden et al., 2005), which woul not be very  parsimonious. Surely, the scaling relation may break down at extreme sides of the spectrum, but the criterion held in physics, which is observing 1/f scaling over at least two decades of frequencies, is generally well met in cognitive performances.

Thirdly, notwithstanding that the idea of identifying processes at different time scales is interesting and seems viable, the theoretical interpretation of the different time scales, and the identification of their source still remains quite speculative. That is, the theoretical underpinnings for how and why exactly the hypothesized processes fluctuate in that specific manner are often underspecified in multi-scaled randomness approaches. The critical question is not whether multiple independent processes could cause 1/f scaling in a measured signal (cf. Wagenmakers et al., 2004; 2005), but rather the specific manner in which those processes must fluctuate. In particular, for any observed 1/f time series, which are many, one needs to examine the number of reasonable time scales involved in the specific process, the approximate values for those time scales, and the relative magnitudes of each influence. The involved processes that evolve at distinct timescales may themselves be as general as corresponding to conscious, preconscious processes, and unconscious processes (Ward, 2002), neural, behavioral and cognitive events (Pressing, 1999), planning and control (Valdez & Amazeen, 2008), or automatic, conscious, and sustained attention (Wagenmakers et al., 2004).

Despite the simplicity of the model itself, the examination of the data is limited to post-hoc accounts for how neural, behavioral and cognitive events, attentional processes, or consciousness components are supposed to overlap (see Torre & Wagenmakers, 2009; Van Orden et al., 2005).

When confronted with the experimental results reviewed above, revealing consistent changes in scaling exponent in different performances, from the fastest neural scales down to the slower behavioral processes, the ‘demystifying’ multi-scaled randomness approach of 1/f in human cognition, in fact, becomes an extraordinary hypothesis in itself. That is, the assumption that the observed behavior is jointly determined by many independent groups of neurons, each with their own different relaxation rate (determined by an autoregressive decay parameter) carries a massive theoretical load. The challenge would be to seek for deficient system components in depression symptoms, retiring red blood cells, as well as in severe constipation, asthma, dyslexia or heart failure, among the many other examples, all happening to line up as a reduced 1/f signature.

3.2 Regime switching
A second perspective on 1/f scaling in human cognition assumes that response processes show discrete transitions from one mode of operation (i.e., a specific mean or variance) to the next. These so-called regime switching models propose that shifts in the mean or the variance of the observed process express shifts in strategy, fatigue or attention. First, it is assumed that, over the course of an experiment, participants repeatedly change strategies. These shifts are employed for only a limited period of time each. During these periods, particular threshold levels determine the criterion amount of accumulation of information required for a response. These changing threshold criteria present themselves as different plateau-like variations (see top panel in Figure 4). Secondly, the speed with which the accumulation process approaches the current threshold is assumed to vary between successive measurements as a first- (or sometimes higher) order autoregressive process (see middle panel in Figure 4). 

Under well-specified parameterizations regime-switching models are able to effectively generate 1/f-like fluctuations (e.g., Wagenmakers et al., 2004; 2005), as shown in the lower panel of Figure 4. Regime-switching models may also account for non-stationarity (i.e., large criterium switches) and sudden switches in performance mode. Cognitive experiments designed to measure the degree of 1/f scaling are generally lengthy, as they usually require 29, 210, or more trials. In those experimental set-ups measured values are sometimes indeed susceptible to undesired effects of learning, fatigue, shifts in strategy and attention, and the like. This means that it is well possible that many short-range dependencies happen to line up as 1/f scaling, showing “that 1/f noise is by no means ubiquitous in psychology” (Farrell, Wagenmakers, & Ratcliff, 2006, p. 740). Specifically, ‘something that looks like’ 1/f scaling may simply cause a coincidental by-product of cognition through fluctuations in fatigue, attention or strategy. 
 
Figure 4. The top panel represents the plateaus induced by the discrete regime switches. The middle panel represents the autoregressive response variability that is inserted to the model. The response series shown in the lower panel was created by dividing the threshold criterion (top panel) by the information accrual time (middle panel), cf. Wagenmakers et al. (2004).

It is admittedly mysterious then, that 1/f scaling is so genuinely observed across across the broadness of time scales of neurology, physiology, motor behavior and cognition, simultaneously. Adding the coincidences (as it applies to independent events in probability theory) associated with the discussed studies underscores that the critical question is not whether strategy, attention, or fatigue fluctuations cause 1/f scaling, but rather the specific manner in which the component activities must fluctuate to cause exactly 1/f scaling, and its variations in the face of experimental manipulation. The associated coincidence renders regime-switching models as poor theoretically viable candidates to account for 1/f scaling in human cognition, lacking any physical motivation.

In addition, one could consider the fact that the broad family of autoregressive moving-average models can reproduce exactly any spectral function after the fact, as long as the spectrum has an asymptotic white region at low frequencies, because the model family has so many free parameters. A first inconvenience, as mentioned before, is that in psychological data the low frequency region does not bend off, suggesting genuine long-range dependence. 

Secondly, the revealance of reduced 1/f scaling in repeated cognitive performances in some of Wagenmakers et al.’s experiments, which would indeed be expected given the postulated multifarious origins, could be explained by the random inter-trial intervals used in these experiments, which was later shown to disrupt scaling (see Holden, Choi, Amazeen, Van Orden, 2011). 

Third, the apparent success of the model is determined by goodness-of-fit per se, and again, realistic data can only be described by a rather narrow set of possible parameter variation (see Gilden, 2009). The question is thus whether a model is a true representation of psychological processes or whether the model itself is so flexible that it is simply able to bend with the measurement error in producing good scores on goodness-of-fit. As Gilden (2009) notes: “Regardless of how small the minimum chi-square is for a particular set of parameter values, one will eventually have to reckon with the fact that the model did not predict that specific outcome; it predicted a range of outcomes, one of which may have happened to look like the data.”.

Wagenmakers and colleagues claim that their componential models are “specified in enough detail to allow a wide range of data to be successfully described and, more important for scientific rigor, predicted” (Wagenmakers et al., 2005, p. 114). The first part of the sentence (i.e., the descriptive part) is obviously true, but disappointedly has little to do with the second part (i.e., prediction). As aptly summarized by Gilden, Wagenmakers et al.’s approach describes so much, it in turn explains very little, and only offers a vehicle for mathematical formalism aimed at post-hoc data fitting, lacking a supporting theoretical literature. Therefore, the theoretical predictions mentioned in the second part of the sentence remain unclear. How do the ARMA model parameters corroborate and predict such consistent changes in the presence of 1/f scaling across such a variety of experimental manipulations? What is the theoretical ground for exactly the fitted parameters? Why is 1/f scaling so allied with coordination in complex systems, being only an artifact? The requisite list of post-hoc explanations required to dismiss 1/f scaling as being functional, across all scales of observation, from the neuron up on to behavior itself, is simply too long, rendering the regime-switching model a rather speculative hypothesis.

3.3	A blend of short and long range correlations
A second prominent theory about 1/f scaling in human performance is the two-source model (Gilden 1997; 2001; 2009; Gilden et al., 1995; Thornton & Gilden, 2005). This model is motivated by the fact that a log-log power spectrum often does not exactly follow a straight line, and may reveal a flattened (hence, whitened) slope at the highest frequencies. 

The high and low-frequency range can thus be modeled in terms of a constrained mixture of two distinct families of variability; white noise and 1/f scaling. These blended sources of variability are referred to as fBmW, where fBm stand for fractional Brownian motion and W for whitened, to emphasize the hybrid structure of whitened 1/f noises.

A fBmW response series has following form: RTn = (1/f α)n + β N(0,1), where RTn is …, (1/f α)n is the nth data point in a 1/f signal with zero mean and unit variance, and N(0,1) denotes a random sample from the normal distribution with zero mean and unit variance. β denotes a free parameter that determines the relative contributions of the white noise component. Accordingly, the power spectrum is built from the correlated and uncorrelated parts in a fBmW signal: S( f ) = N(α) f α + β2, where β2 is the fraction of variance in the random process attributable solely to white noise (see Figure 5).

 

Figure 5. The top left panel shows a white noise signal, which was added to the 1/f scaling in the lower left panel to construct the power spectrum in the right panel, which reveals fBmW noise, as indicated by the flattened slope at the highest frequencies, shown as a solid line. The dashed line represents the ideal 1/f scaling slope.

A difference between Gilden et al.’s account and the two models previously described is that 1/f scaling is conceived of as residing from a functional part of the cognitive system, rather than as a statistical artifact. In the approach of Gilden and colleagues, the presence of 1/f scaling represents a genuine fractal process, indicating that cognitive processes are complex across multiple temporal scales. A natural prediction is that 1/f scaling is generic to the behavior of cognitive systems, and an intrinsic property of the system. 

At the other hand one could note that 1/f scaling is not exactly seen as a dynamical signature of an entirely integrated system either. 1/f scaling is rather hypothesized to reflect the self-organization of a component within the system, a component that is associated with elementary aspects of cognition, including the goals, intentions, and representations of a participant. Specifically, Gilden (2001) postulated that intrinsic fluctuations of a memory module, which serves the purpose of continuity of ‘mental set’, are potentially causal in the formation of 1/f scaling. Other processes, e.g. motor processes, constitute a source of contaminating white noise, and human performances constitute an additive blend of a complex 1/f process and the pure white noise signal, in varying degrees in different performances. 

The two-source approach fits in with more traditional models, where cognitivist dual system models are common. The mental set hypothesis may explain why the presence of 1/f scaling is reduced in cognitive performances when the task is not constant across trials. For instance, when task parameters change unpredictably, mental set is interrupted, which will induce trial independence in responses, resulting in scaling properties closer to white noise. An example given by Gilden (2001) is task switching. This interpretation appears viable if one considers the varying degree of 1/f scaling in the four tasks presented in Figure 2. Specifically, Thornton and Gilden (2005) presented a detailed account for Figure 2 based on their model, by showing that temporal estimation tasks (comparable with the precision aiming task in Figure 2 for the present purpose) not only reveals clear 1/f scaling, but also a contribution of the white noise component, while a choice reaction task shows less clear 1/f scaling, with a much stronger white noise contribution, and word-naming data reveal the least clear presence of 1/f scaling, and the strongest contribution of white noise. It thus appears that the model adequately describes a subset of the discussed data. 

Nonetheless, the model does not specify specifically which of the dual components in the model would change specifically, and specifically why or how the error term gives complementary information. The presented results also suggest that an independent system component attributed to mental set (Gilden, 2001) or vigilance (Gilden & Hancock, 2007) might be too limited in scope to account for all shared instances between 1/f scaling and coordination in brain, body and behavior, across the measurement scales involved.

A related  approach to 1/f scaling originates from Delignières and colleagues, and has been applied primarily to rhythmical movements. These authors have presented a series of concrete models, each specific to a well-defined domain of motor performance, that effectively mimic empirically observed scaling properties. Like Gilden, their approach is to insert a local source of 1/f scaling in statistically well-defined, local parts of traditional cognitive models, to account for the relative presence of 1/f scaling and specific spectral deviations thereof. As an example, Delignieres, Torre, and Lemoine (2008) adapted the Wing-Kristofferson model (1973) for finger tapping, by inserting fractal properties, into the cognitive timekeeper module assumed by the traditional model, using the regime-switching model previously discussed. Their model accounted for the scaling properties of self-paced tapping. Other examples include synchronized tapping (Torre & Delignières, 2008a), and forearm oscillations (Delignières et al., 2008).

Delignières et al. point out that their purpose is to account for the workings of a particular, domain-specific component encapsulated in the system, and use 1/f noise as a constraint for modeling. Sources of 1/f scaling are taken to represent complex timekeeping processes that can be statistically localized in components within the system. Thus from this perspective, 1/f scaling represents a functional aspect of human performance related to cognitive timekeeping, but the different source of 1/f scaling in each domain-specific application has the form of a fractal generator that, together with non-fractal components, makes up the dynamics of repeated responses.

Mechanistic (i.e., two-source) modeling has the advantage to be experimentally testable and thus falsifiable, and allows establishing links to current models of sensorimotor behavior. There is no a priori reason why long-range and short-range dependence should be mutually exclusive (cf. Van Orden et al., 2005; Wagenmakers et al., 2005), and thus the observed serial correlations are possibly the result of both, and mechanistic models provide a route to separate the long-range from the short-range components. Separation of variance components led to good fits to empirical data in specific tasks, under the assumption that different system components are responsible for the differences in performance (e.g., Delignières & Torre, 2011). 

Interestingly, the timekeeping hypothesis proposed by Delignières and colleagues appears to be consistent with the lack in 1/f scaling when participants synchronize to a metronome (i.e., an external timekeeper) evidenced in tapping and walking experiments as discussed previously.

The concern, again, is the approach of post-hoc data fitting. While good data fits may be compelling, agreement between model and data is not proof that the model is correct (cf. Gilden, 2009). The pitfall of mechanistic modeling is that one may mistakenly believe that a good quantitative model fit equals qualitative or theoretical insight. A good fit to the data is a necessary, but not a sufficient criterion for a model’s usefulness (Roberts & Pashler, 2000). A consideration of a model’s usefulness involves, for instance, also a consideration of the theoretical foundations, the extent to which the model points to new research directions, and the generalizability of the model. 

Advanced data fitting may lead to an indefinite number of fractal generators throughout brain, body and cognition, possibly leading to multiple competing models capable of equally compelling fits to the data (Gilden, 2009; Hasselman, Seevinck, & Cox, 2011), which would question in itself the tenability of domain-specific theoretical explanations of 1/f scaling (Kello et al., 2007). Specifically, a full account for the reviewed studies would require domain-specific models for each of the observations across scientific domains, and scales of observation. Although this could arguably lead to a well-fitting model for each separate phenomenon, that approach would lack the coherence of a solid theoretical framework over brain, body and cognition necessitated. 

3.4	Interaction-dominant dynamics
1/f scaling is a typical behavior of self-organizing systems, which reflects a fundamental aspect of all physiological and cognitive functions: their emergence in the balance of independent versus interdependent component activities. Interaction-dominance postulates that the cognitive system actually uses this “flexible stability” to its own advantage by exploiting the interdependencies among ongoing processes over a multiplicity of interdependent scales, allowing for a coordinative basis of cognitive function (e.g., Kello et al., 2007; Kello, 2011; Van Orden et al., 2011; Wijnants et al., 2009;), and suggesting a common control mechanism among brain, body and cognition, across the full range of scales involved.

This perspective conceives 1/f scaling as the natural outcome of complex, living systems. In the true physical sense, complex systems consist of a set of interrelated and interdependent parts with an almost infinite amount of degrees-of-freedom that cohere into a coordinated functional system. The system components dynamically interact in nonlinear ways at multiple embedding time scales, so that the intrinsic dynamics of the components matter less than the mutual interactions among components. This position is a departure from the more traditional view on human cognition that conceives human performance as caused by a number of discrete components (i.e. independent regions of the brain, internal clocks or other information-processing devices), whose internal dynamics, when integrated, account for the observed performance. This convention can be referred to as component-dominant dynamics because the intrinsic activities of the components are held to be much more influential, much more dominant in determining the observed performance, than the interactions among the components.

The starting point of the interaction-dominance approach is that the conventional way of thinking about cognitive processes underestimates the number of temporal scales on which cognitive activity is actually assembled. The interaction-dominant perspective claims that cognition is more than a collection of independent processes operating in a modular cognitive system, and entails that the same processes govern cognitive performance in very short (i.e., neural) and very long time frames (e.g., behavior). Any measured behavior nests processes at faster time scales, and in turn, is nested within processes at even slower time scales, and the behavior of any one process at any one time scale is susceptible to, and reflective of, the behaviors of all processes evolving over shorter scales. This means that the many processes involved interact so completely, up to the periphery of the nervous system, that one can no longer parse the individual activity of any component apart, which reveals itself through widespread scaling relations, as the essential outcome the interdependence among components across multiple scales.

In interaction-dominant systems control is distributed rather than localized as in specialized devices that form efficient causes for behavior. Coordinated system performance is therefore taken to emerge through the interdependence and cooperation of processes that operate at many timescales simultaneously. The tight coupling of mutually constraining timescales of performance, as in 1/f scaling, through self-organization (the spontaneous organization that coordinates system behavior in the absence of a central controller) and emergence (the appearance of features that are not implicit in the parts of the system), in an a priori prediction.

Interaction-dominance is a viable explanation for the presence, and the relative changes in the presence, of 1/f scaling in the activity of brain, body, motor system, and cognition. Self-organization parsimoniously explains that 1/f scaling is so generic to the behavior of such a wide variety of embodied processes. To give rise to 1/f scaling, a system does not depend on the behavior of a specific sub-system, but rather coordinates its behavior system-wide. As a consequence, one can not dissect functionally entangled phenomena into component processes. Coordinated system consist of entangled processes evolving over a multitude of temporal scales, observed as a clear fractal signal. A further natural prediction from interaction-dominance, confirmed empirically, is that external perturbations to the system reduce, or de-correlate the 1/f signal.
   
Nonetheless, some authors remain reticent and cautious to embrace an interaction-dominant position to the study of cognitive phenomena. For one, Wagenmakers et al. (2005) have argued that 1/f noise is not a unique property of interaction-dominant systems, nor do all interaction-dominant systems display 1/f scaling under all circumstances. Wagenmakers et al. (2011) have taken a pile of salt as an example. It remains unclear however, whether this abstract example truly invalidates the broad linkages between 1/f scaling and human coordination presented here. In contrast, what this argument underscores is that all model systems, like rice piles, need to be tuned to elicit the emergent behavior. This illustrates just how hard the scaling by coincidence hypothesis is to maintain for complex living systems.

Another issue is whether concepts and mathematical tools from nonlinear dynamical science to cognitive phenomena can lead to a notable advance in the understanding of those phenomena, if such applications are not accompanied by concrete mechanistic models. That is, some scientists have argued that, in order for interaction-dominance to be testable and falsifiable, the equations that govern the system should be written out (Diniz et al., 2010; Wagenmakers et al., 2005). As it stands, however, reproducing 1/f by a model is not sufficient, since many mechanisms can lead to the same scaling behavior, but with different nonlinear and multifractal properties that do not match the behavior of the studied system.

Van Orden et al. (2005) have spelled out some of the difficulties that arise at this point. For one, “there is presently no workable entry level below the level of the emergent phenomena themselves” (p. 121). While it seems doable to postulate adequate models that describe separately the functioning of, for instance, red blood cells, motor behavior or brain activity, it remains unclear as to at which of these levels one should start in a reduction of an interaction-dominant system in the true physical sense. In other words, “emergent macrolevel behavior is antithetical to the conventional reductive pursuit of cognitive mechanisms.” (Van Orden et al., 2005, p. 121). Therefore, support for interaction-dominance must come from either empirical results (i.e., observing consistent changes in the presence of 1/f scaling following careful experimental manipulations) or other phenomena that reveal analogous self-organizing properties (i.e., convection rolls or ecosystems; Jensen, 1998; Jørgensen, Mejer, & Nielsen, 1998; Van Orden et al., 2003), and neural network models (Bertschinger & Natschlager, 2004; Kwok & Smith, 2005). 

In the context of models that generate 1/f scaling, there have been important developments after the proposition of the multi-scaled randomness and the two-source model mechanism that complement earlier analogies with simplified physical models (i.e., an Ising model, see Kello & Van Orden, 2009, or a sandpile model, see Bak, Tang & Wiesenfeld, 1987). Some of these efforts have been successfully applied in cognitive science (e.g., Delignières & Marmelat, 2012; Kello, 2013) to generate scaling that holds for a range of model parameters However, no single model family currently seems able to coherently capture the widespread scaling relations empirically observed across the fast neural scales down to the slower scale of human behavior and cognition. 

3.	Conclusion
In this paper a discussion is provided about the linkage between the presence of 1/f scaling and coordinated brain, motor and cognitive activities. Specifically, it has been argued that 1/f fluctuations govern healthy, flexibly-stable systems, regardless of the scale of observation, from the level of the cell up to the level of brain, body, and cognition. 1/f scaling has triggered a lot of controversy over recent years as an empirical phenomenon. Therefore, the goal of the present paper was to advance this debate, by focusing on a broad range of empirical observations that transcend the boundaries between scientific domains. The discussion focused on different perspectives that seek theoretically motivated accounts for these findings.

The question posed was how to understand the close linkage between 1/f scaling and system coordination. The goal was to promote answering the harder type of questions based on this linkage. What do the systematic fluctuations observed in the performance of so many different studied systems signify? Do these fluctuations constitute errors, or do they play a functional role? How and why is long-term stability associated with short-term flexibility when system behavior is governed by 1/f scaling? While all of the discussed approaches may potentially account for the presence of 1/f scaling per se, the specific suggestion here was to rephrase the question as to which of the approaches accounts best for the so general linkage between observed fractal dynamics and coordination in the analyzed system.

Wagenmakers et al. have laid out an argument showing that the presence of 1/f scaling (per se) should not be taken as evidence for self-organization and complexity. The argument refutes the enterprise of observing (some extent of) 1/f scaling in some measure in some task and concluding, based upon that observation, that the system under scrutiny is complex. The goal of the present paper was actually to step beyond a discussion about the presence versus non-presence of genuine 1/f scaling, however, and to question instead how and why it is that 1/f scaling changes so consistently across different manipulations of task, condition, and level of analysis. For example, why would cognition be short-range? Why this exception in the context of fractal scaling at all other scales of the system?

In their respective approaches, Gilden and colleagues as well as Delignières and colleagues, have focused specifically on observed changes in the extent of 1/f scaling, including changes that may emerge from nonlinearity in the power spectra, but if cognitive components are independent and domain-specific, why is fractal scaling evident throughout the entire system?
Furthermore it remains unclear whether two-source models can include other complexity measures as well (e.g., Ashkenazy et al., 2001; Ivanov, 1996; Ivanov et al., 2001; Ivanov et al., 2009; Ivanov, Amaral, & Goldberger, 1999; Hu et al., 2004).

While the perspectives presented by Wagenmakers and colleagues and Delignières and collegues are yet to account for the generality of the association between 1/f scaling and coordinated human activities, Gilden’s model is in fact much more widely applicable and generalizable (see Gilden, 2009). It is unclear however, whether the distinction between cognitive 1/f noise and random motor noise remains tenable given the thin line separating motor behaviors from cognitive behaviors (i.e., the radical embodiment thesis). Also the accompanying phenomenological account (hence, breakdown of mental set or vigilance) might be to narrow to account for the totality of presented changes in the extent of 1/f scaling. The perspective of interaction-dominance, however, does provide one general explanation for the reviewed studies, using principles of self-organized control.

Embracing interaction-dominance requires stepping beyond the traditional modular view of human cognition. If one considers the unexpectedness of the observations presented, however, based on a modular approach it is clear that the post-hoc explanations required are massive. In addition, the modular defense has not gone any much further than simply expressing the opinion that studies that include 1/f scaling are too “limited, superficial, and overly general” (Wagenmakers et al., 2011, p. 4) to be of any use, which simply ignores the empirical outcomes, and the broadness of scales to which they apply. Under the current state of affairs, therefore, it seems unwarranted to categorize studies addressing the functional role of 1/f scaling in behavior as “mostly speculation, wrapped in jargon, inside wishful thinking” (Wagenmakers et al., 2011, p. 5). Quite to the contrary, although many questions remain to be answered and important challenges lie ahead, studying 1/f scaling and allied concepts of interdependence in human performances arguably has the potential to answer the tougher type of question about the scales and modes involved in coordinated human activities.

 

References

Abásolo, D., Hornero, R., Gómez, C., García, M., López, M. (2006). Analysis of EEG background activity in Alzheimer's disease patients with Lempel-Ziv complexity and central tendency measure. Medical Engineering and Physics, 28(4), 315-322. doi: 10.1016/j.medengphy.2005.07.004
Auriel, E., Hausdorff, J. M., Herman, T., Simon, E. S., & Giladi, N. (2006). Effects of methylphenidate on cognitive function and gait in patients with Parkinson’s disease: A pilot study. Clinical Neuropharmacology, 29, 15-17. doi:10.1097/00002826-200601000-00005
Ashkenazy, Y., Ivanov, P. C., Havlin, S., Peng, C.-K., Goldberger, A. L., & Stanley, H. E. (2001). Magnitude and sign correlations in heartbeat fluctuations. Physical Review Letters, 86, 1900-1903.
Ashkenazy, Y, Hausdorff, J. M., Ivanov, P. C., Goldberger, A. L., & Stanley, H. E. (2002). A stochastic model of human gait dynamics. Physica A, 316, 662-670. 
Bahrami, B., Seyedsadjadi, R., Babadi, B., Noroozian, M. (2005). Brain complexity increases in mania. NeuroReport, 16, 187–191. doi:10.1097/00001756-200502080-00025
Bak, P., Tang, C., & Wiesenfeld, K. (1987). Self-organized criticality: an explanation of 1 / f noise. Physical Review Letters, 59, 381–384. doi:10.1103/PhysRevLett.59.381
Bassingthwaighte, J. B., Liebovitch, L. S., West, B. J. (1994). Fractal Physiology. Oxford: University Press. 
Beran, J. (1994). Statistics for long-memory processes. New York: Chapman & Hall.
Bertschinger, N., & Natschlager, T. (2004). Real-time computation at the edge of chaos in recurrent neural networks. Neural Computation, 16, 1413–1436. doi:10.1162/089976604323057443
Bhattacharya, J., Edwards, J., Mamelak, A. N., & Schuman, E. M. (2005). Long-range temporal correlations in the spontaneous spiking of neurons in the hippocampal-amygdala com-plex of humans. Neuroscience, 131(2), 547–555. doi:10.1016/j.neuroscience.2004.11.013
Bressler, S. L., & Kelso, J. A. S. (2001). Cortical coordination dynamics and cognition. Trends in Cognitive Sciences, 5(1), 26-36. doi:10.1016/S1364-6613(00)01564-3
Brogan, T. V., Mellema, J. D., Martin, L. D., Krueger, M., Redding, G. J., & Glenny R. W. (2007). Spatial and temporal heterogeneity of regional pulmonary blood flow in piglets. Pediatric Research, 62, 434–439. doi:10.1203/PDR.0b013e31814625a0
Burr, R. L., Kirkness, C. J., & Mitchell, P. H. (2008). Detrended fluctuation analysis of intracranial pressure predicts outcome following traumatic brain injury. IEEE Transactions on Biomedical Engineering, 55(11), 2509-2518. doi:10.1109/TBME.2008.2001286
Buzsàki, G. (2006). Rhythms of the brain. New York, NY: Oxford University Press.
Chen, Y., Ding, M., & Kelso, J. A. S. (1997). Long memory processes (1/fα type) in human coordination. Physical Review Letters, 79, 4501–4504. doi:10.1103/PhysRevLett.79.4501
Clayton, K., & Frey, B. B. (1997). Studies of mental “noise.” NonlinearDynamics, Psychology, and Life Sciences, 1, 173–180.
Collins, J.J., & De Luca, C. J. (1993). Open-loop and closed-loop control of posture: a random-walk analysis of center-of-pressure trajectories. Experimental Brain Research, 95, 308–318. doi:10.1007/BF00229788
Collins, J. J., & De Luca, C. J. (1995). Upright, correlated random walks: A statistical 16 biomechanics approach to the human postural control system. Chaos, 5, 57-63.
Correll, J. (2008). 1/f noise and effort on implicit measures of racial bias. Journal of Personality and Social Psychology, 94, 48–59. doi:10.1037/0022-3514.94.1.48
Correll, J. (2011). Order from chaos? 1/f noise predicts performance on reaction time measures. Journal of Experimental Social Psychology, 47, 830-835.  doi:10.1016/j.jesp.2011.02.019
Costa, M., Ghiran, I., Peng, C.-K., Nicholson-Weller, A., Goldberger, A. L. (2008). Complex dynamics of human red blood cell flickering: Alterations with in vivo aging. Physics Review E, 78(2), 20901- 20905. doi:  10.1103/PhysRevE.78.020901
Delignières, D. & Marmelat, V. (2012). Fractal fluctuations and complexity: Current debates and future challenges. Critical Reviews in Biomedical Engineering, 40(6), 485-500.
Delignières, D. & Torre, K. (2009). Vers une nécessaire prise en compte de la complexité : Variabilité et fractalité dans la motricité rythmique. Intellectica, 52, 41-54.
Delignières, D. & Torre, K. (2011). Event-based and emergent timing: dichotomy or continuum? A reply to Repp and Steinman (2010). Journal of Motor Behavior, 43, 311-318. doi:10.1080/00222895.2011.588274
Delignières, D., Torre, K., & Lemoine, L. (2008). Fractal models for event-based and dynamical timers. Acta Psychologica, 127, 382–397. doi:10.1016/j.actpsy.2007.07.007
Diniz, A., Wijnants, M. L., Torre, K., Barreiros, J., Crato, N., Bosman, A. M. T., Hasselman, F., Cox, R. F. A., Van Orden, G., & Delignières, D. (2011) Contemporary theories of 1/f noise in motor control. Human Movement Science, 30, 889-905. doi:10.1016/j.humov.2010.07.006.
Dixon, J. A., Holden, J. G., Mirman, D., & Stephen, D. G. (in press). Multifractal dynamics in the emergence of cognitive structure. topiCS.
Doyle, T. L. A., Dugan, E. L., Humphries, B., & Newton, R. U. (2004). Discriminating between elderly and young using a fractal dimension analysis of centre of pressure. International Journal of Medical Sciences, 1(1): 11–20. 
Doyle, T. L. A., Newton, R. U., & Burnett, A. F. (2005). Reliability of traditional and fractal dimension measures of quiet stance center of pressure in healthy young people. Archives of Physical Medicine and Rehabilitation, 86, 2034-2040.
Duarte, M., & Sternad, D. (2008). Complexity of human postural control in young and older adults during prolonged standing. Experimental Brain Research, 191(3):265-276. doi:10.1007/s00221-008-1521-7
Duarte, M., & Zatsiorsky, V. M. (2001). Long-range correlations in human standing. Physics Letters A, 283, 124–128. doi:10.1016/S0375-9601(01)00188-8
Eke, A., Hermán, P., Kocsis, L., & Kozak, L. R. (2002). Fractal characterization of complexity in temporal physiological signals. Physiological Measurement, 23, 1–38. doi:10.1088/0967-3334/23/1/201
Farrell, S., Wagenmakers, E.-J., & Ratcliff, R. (2006). 1/f noise in human cognition: Is it ubiquitous, and what does it mean? Psychonomic Bulletin & Review, 13, 737-741. doi:10.3758/BF03193989
Fitts, P. M. (1954). The information capacity of the human motor system in controlling the amplitude of movement. Journal of Experimental Psychology: General, 47, 381–391. doi:10.1037/h0055392
Freeman, W. J., Burke, B. C., Holmes, M. D., & Vanhatalo, S. (2003). Spatial spectra of scalp EEG and EMG from awake humans. Clinical Neurophysiology, 114(6),1053–1068.  doi:10.1016/S1388-2457(03)00045-2
Frey, U., Brodbeck, T., Majumdar, A., Taylor, D. B., Town, G. I., Silverman, M., & Suki, B. (2005). Risk of severe asthma episodes predicted from fluctuation analysis of airway function. Nature, 438, 667-670. doi:10.1038/nature04176
Gardner, M. (1978). Mathematical games: White and brown music, fractal curves and one-over-f fluctuations. Scientific American, 238,16-32.
Gibbs, R., & Van Orden, G. (2012). Pragmatic choice in conversation. topiCS, 4, 7-20..
Gilden, D. L. (1997). Fluctuations in the time required for elementary decisions. Psychological Science, 8, 296–301. doi:10.1111/j.1467-9280.1997.tb00441.x
Gilden, D. L. (2001). Cognitive emissions of 1/f noise. Psychological Review, 108, 33-56. doi:10.1037//0033-295X.108.1.33
Gilden, D. L. (2009). Global model analysis of cognitive variability. Cognitive Science, 33, 1441–1467. doi:10.1111/j.1551-6709.2009.01060.x
Gilden, D. L., & Hancock, H. (2007). Response variability in attention deficit disorders. Psychological Science, 18, 796–802. doi:10.1111/j.1467-9280.2007.01982.x
Gilden, D. L., Thornton, T. L., & Mallon, M. W. (1995). 1/f noise in human cognition. Science, 267, 1837-1839. doi:10.1126/science.7892611
Giugliano, M., Darbon, P., Arsiero, M., Luescher, H. R., & Streit, J. (2004). Single neuron discharge properties and network activity in dissociated cultures of neocortex. Journal of Neurophysiology, 92, 977–996. doi:10.1152/jn.00067.2004
Goldberger, A. L. (1997). Fractal variability versus pathologic periodicity: complexity loss and stereotypy in disease. Perspectives in Biology and Medicine, 40, 543-561.
Goldberger, A.L., Peng, C.-K., & Lipsitz, L. A. (2002). What is physiologic complexity and how does it change with aging and disease? Neurobiology of Aging, 23, 23–26. doi:10.1016/S0197-4580(01)00266-4
Govindan, R. B., Wilson, J. D., Murphy, P., Russel, W. A., & Lowery, C. L. (2007). Scaling analysis of paces of fetal breathing, gross-body and extremity movements. Physica A, 386, 231–9.  doi:10.1016/j.physa.2007.08.021
Granger, C. W. J. (1980). Long memory relationships and the aggregation of dynamic models. Journal of Econometrics, 14, 227-238. doi:10.1016/0304-4076(80)90092-5
Grüneis, F., Nakao, M., Mizutani, Y., Yamamoto, M., Meesmann, M. & Musha, T. (1993). Further study on 1/f fluctuations observed in central single neurons during REM sleep. Biological Cybernetics, 68(3), 193–198. doi:10.1007/BF00224851
Ha, T. H., Yoon, U., Lee, K. J., Shin, Y. W., Lee, J.-M., Kim, I. Y., Ha, K. S., Kim, S. I., & Kwon, J. S. (2005). Fractal dimension of cerebral cortical surface in schizophrenia and obsessive-compulsive disorder. Neuroscience Letters, 384, 172-176. doi:10.1016/j.neulet.2005.04.078
Harrison, K. H., Hof, P. R., & Wang, S. S.-H. (2002). Scaling laws in the mam¬malian neocortex: does form provide clues to function? Journal of Neurocytology, 31, 289–298. doi: 10.1023/A:1024178127195
Hausdorff, J. M. (2007). Gait dynamics, fractals and falls: finding meaning in the stride-to-stride fluctuations of human walking. Human Movement Science, 26, 555–589. doi:10.1016/j.humov.2007.05.003
Hausdorff, J. M. (2009). Gait dynamics in Parkinson's disease: common and distinct behavior among stride length, gait variability, and fractal-like scaling. Chaos 19(2), 026113.
Hausdorff, J. M., Ashkenazy, Y., Peng, C-K, Ivanov, P. C., Stanley, H. E., & Goldberger, A. L. (2001). Physica A, 302, 138-147. 
Hausdorff, J. M., & Peng, C.-K. (1996). Multiscaled randomness: A possible source of 1/ f noise in biology. Physical Review E, 54, 2154-2157. doi:10.1103/PhysRevE.54.2154
Hasselman, F., Seevinck, M.P., & Cox, R.F.A. (2011). Caught in the undertow: The structure beneath the ontic stream. Manuscript submitted to Journal of Experimental and Theoretical Artificial Intelligence.
Holden, J. G. (2005). Gauging the fractal dimension of response times from cognitive tasks. In M. A. Riley & G.  C. Van Orden (Eds.), Contemporary nonlinear methods for behavioral scientists: A webbook tutorial, 267-318. http://www.nsf.gov/sbe/bcs/pac/nmbs/nmbs.jsp

Holden, J. G., Choi, Y., Amazeen, P. G., & Van Orden, G. (2011). Fractal 1/f dynamics suggest entanglement of measurement and human performance. Journal of Experimental Psychology: Human Perception and Performance, 37, 935-948.
Hu, K, Ivanov, P. C., Hilton, M. F., Chen, Z., Ayers, R. T., Stanley, H. E., & Shea, S. A. (2004). Endogenous circadian rhythm in an index of cardiac vulnerability independent of changes in behavior. Proceedings of the National Academy of Sciences of the United States of America, 101, 18223-18227.
Ihlen, E. A. F., & Vereijken, B. (2010). Interaction-dominant dynamics in human cognition: Beyond 1/fα fluctuation. Journal of Experimental Psychology: General, 139, 436-463. doi:10.1037/a0019098
Ivanov, P.C., Amaral, L. A. N., Goldberger, A. L., Havlin, S., Rosenblum, M. G., Stanley, H. E., & Struzik, Z. R. (1999). Multifractality in human heartbeat dynamics, Nature, 399, 461-465.
Ivanov, P. C., Amaral, L. A. N., Goldberger, A. L., Havlin, S., Rosenblum, M. G., Struzik, Z. R, & Stanley, H. E. (1996). Scaling behaviour of heartbeat intervals obtained by wavelet-based time-series analysis, Nature, 383, 323-327. 
Ivanov, P. C., Bunde, A; Amaral, L. A. N., Havlin, S., Fritsch-Yelle, J., Baevsky, R. M., Stanley, H. E., & Goldberger, A. L. (1999). Sleep-wake differences in scaling behavior of the human heartbeat: Analysis of terrestrial and long-term space flight data. Europhysics Letters, 48, 594-600.
Jensen, H. J. (1998). Self-organized criticality. Cambridge, England: Cambridge University Press.
Jørgensen, S. E., Mejer, H., & Nielsen, S. N. (1998). Ecosystem as self-organizing systems. Ecological Modelling, 111, 261-268. doi:10.1016/S0304-3800(98)00104-5
Kantelhardt, J. W., Ashkenazy, Y, Ivanov, P. C., Bunde, A, Havlin, S., Penzel, T., Peter, J-H, Stanley, H. E. (2002).  Characterization of sleep stages by correlations in the magnitude and sign of heartbeat increments. Physical Review E, 65.
Karasik, R; Sapir, N, Ashkenazy, Y., Ivanov, P. C., Dvir, I., Lavie, P., & Havlon, S. (2002). Correlation differences in heartbeat fluctuations during rest and exercise. Physical Review E, 66.
Karperien, A. L., & Jelinek, H. F. (2008). Box-counting analysis of microglia form in schizophrenia, Alzheimer’s disease, and affective disorder. Fractals 16, 103–107. doi:10.1142/S0218348X08003880
Kello, C. T. (2013). Critical branching neural networks. Psychological Review, 120, 230-254.
Kello, C. T., Anderson, G. G., Holden, J. G., & Van Orden, G. C. (2008). The pervasiveness of 1/f scaling in speech reflects the metastable basis of cognition. Cognitive Science, 32, 1217–1231. doi:10.1080/03640210801944898
Kello, C. T., Beltz, B. C., Holden, J. G., & Van Orden, G. (2007). The emergent coordination of cognitive function. Journal of Experimental Psychology: General, 136, 551-568. doi:10.1037/0096-3445.136.4.551
Kello, C. T., & Van Orden, G. (2009).  Soft-assembly of sensorimotor function.  Nonlinear Dynamics in Psychology and the Life Sciences, 13, 57-78.
Kiefer, A. W., Riley, M. A., Shockley, K., Villard, S., & Van Orden, G. C. (2009). Walking changes the dynamics of cognitive estimates of time intervals. Journal of Experimental Psychology: Human Perception and Performance, 35(5), 1532–1541. doi:10.1037/a0013546
Kniffki, K.-D., Pawlak, M., Vahle-Hinz, C. (1994). “Fractal dimension and dendritic branching of neurons in the soimatosensory thalamus,” in Fractals in Biology and Medicine, eds T. F. Nonnenmacher, G. Losa, and E. R. Weibel (Basel: Birkhauser Verlag), 221–229.
Kwok, T., & Smith, K. A. (2005). Optimization via intermittency with a self-organizing neural network. Neural Computation, 17, 2454–2481. doi:10.1162/0899766054796860
Lai, M. C., Lombardo, M. V., Chakrabarti, B., Sadek, S. A., Pasco, G., Wheelwright, S. J., Bullmore, E. T., Baron-Cohen, S., MRC AIMS Consortium, & Suckling, J. (s2010). A shift to randomness of brain oscillations in people with autism. Biological Psychiatry, 68, 1092-1099. doi:10.1016/j.biopsych.2010.06.027
Laughton, C. A., Slavin, M., Katdare, K., Nolan, L., Bean, J. F., Kerrigan, D. C., Phillips, E., Lipsitz, L. A., & Collins, J. J. (2003). Aging, muscle activity, and balance control: physiologic 3 changes associated with balance impairment. Gait & Posture, 18, 101-108. doi:10.1016/S0966-6362(02)00200-X
Liebovitch L. S., & Krekora P. (2002). The physical basis of ion channel kinetics: the importance of dynamics. in H. E. Layton, & A. M. Weinstein (eds.) Institute for Mathematics and its Applications Volumes in Mathematics and Its Applications, Membrane Transport and Renal Physiology Volume 129, (pp. 27-52). Berlin: Springer-Verlag.
Liebovitch, L.S., & Shehadeh, L. A. (2005). Introduction to fractals. In M. A. Riley & G. Van Orden (Eds.), Contemporary nonlinear methods for behavioral scientists: A webbook tutorial, 178-266. http://www.nsf.gov/sbe/bcs/pac/nmbs/nmbs.jsp 
Linkenkaer-Hansen, K., Monto, S., Rytsälä, H., Suominen, K., Isometsä, E., & Kähkönen, S. (2005). Breakdown of long-range temporal correlations in theta oscillations in patients with major depressive disorder. The Journal of Neuroscience, 25, 10131–10137. doi:10.1523/JNEUROSCI.3244-05.2005
Lowen, S. B., Cash, S. S., Poo, M.-M., & Teich, M. C. (1997). Quantal neu¬rotransmitter secretion rate exhib¬its fractal behavior. The Journal of Neuroscience, 17, 5666–5677. http://people.bu.edu/teich/pdfs/JN-17-5666-1997.pdf
Mäkikallio, T. H., Huikuri, H. V., Hintze, U., Videbæk, J., Mitrani, R. D., Castellanos, A., Myerburg, R. J., & Møller, M. (2001). Fractal analysis and time- and frequency-domain measures of heart rate variability as predictors of mortality in patients with heart failure. American Journal of Cardiology, 87(2),178–182. doi:10.1016/S0002-9149(00)01312-6
Manabe, Y., Honda, E., Shiro, Y., Sakai, K., Kohira, I., Kashihara, K., Shohmori, T., & Abe, K. (2001). Fractal dimension analysis of static stabilometry in Parkinson's disease and spinocerebellar ataxia. Neurological Research, 23(4), 397-404.
Maurer, C., Mergner, T., & Peterka, R. J. (2004). Abnormal resonance behavior of the postural 9 control loop in Parkinson’s disease. Experimental Brain Research, 157, 369-376. doi:10.1007/s00221-004-1852-y
Mendonca, G. V., Pereira, F. D., & Fernhall, B. (2011). Fractal scaling properties of heart rate dynamics in persons with Down syndrome. Autonomic Neuroscience: Basic and Clinical, 161, 110-115. doi:10.1016/j.autneu.2010.12.007
Milosevic, N. T., Ristanovic, D., Stankovic, J. B., & Gudovic, R. (2007). Fractal analysis of dendritic arborisation pat¬terns of stalked and islet neurons in substantia gelatinosa of different spe¬cies. Fractals, 15(1), 1–6. doi:10.1142/S0218348X07003411
Mutch, W. A. C., Harms, S., Lefevre, G. R., Graham, M. R., Girling, L. G., & Kowalski, S. E.  (2000). Biologically variable ventilation increases arterial oxygenation over that seen with positive end-expiratory pressure alone in a porcine model of acute respiratory distress syndrome. Critical Care Medicine, 28(7), 2457-2464. doi:10.1097/00003246-200007000-00045
Ogata, H., Tokuyama, K., Nagasaka, S., Ando, A., Kusaka, I., Sato, N., Goto, A., Ishibashi, S., Kiyono, K., Struzik, Z. R., & Yamamoto, Y. (2007). Long-range correlated glucose fluctuations in diabetes. Methods of Information in Medicine, 46(2), 222-226. 
Peng, C.-K., Havlin, S., Hausdorff, J. M., Mietus, J. E., Stanley, H. E., & Goldberger, A. L. (1995). Fractal mechanisms and heart rate dynamics: Long-range correlations and their breakdown with disease. Journal of Electrocardiology, 28, 59-65. doi:10.1016/S0022-0736(95)80017-4
Peng, C.-K., Mietus, J. E., Liu, Y., Lee, C.,  Hausdorff, J. M., Stanley, H. E., Goldberger, A. L., & Lipsitz, L. A. (2002). Quantifying fractal dynamics of human respiration: age and gender effects. Annals of Biomedical Engineering, 30(5), 683-692. doi:10.1114/1.1481053
Pierigè, F., Serafini, S., Rossi, L., & Magnani, M. (2008). Cell-based drug delivery. Advanced Drug Delivery Reviews, 60(2), 286–295. doi:10.1016/j.addr.2007.08.029.
Pressing, J. (1999). Sources for 1/ f noise effects in human cognition and performance. Journal for Interdisciplinary and Cross-Cultural Studies, 2, 42-59.
Pressing, J., & Jolley-Rogers, G. (1997). Spectral properties of human cognition and skill. Biological Cybernetics, 76, 339-347. doi:10.1007/s004220050347
Priplata, A. A., Niemi, J. B., Harry, J. D., Lipsitz, L. A., & Collins, J. J. (2003). Vibrating insoles and balance control in elderly people. Lancet, 362, 1123-1124. doi:10.1016/S0140-6736(03)14470-4
Priplata, A. A., Patritti, B. L., Niemi, J. B., Hughes, R., Gravelle, D. C., Lipsitz, L. A., Veves, A., Stein, J., Bonato, P., & Collins, J. J. (2006). Noise-enhanced balance control in patients with diabetes and patients with stroke. Annals of Neurology, 59, 4-12. doi:10.1002/ana.20670
Ramon, C., Holmes, M. D., Freeman, W. J., McElroy, R., & Rezvanian, E. (2008). Comparative analysis of temporal dynamics of EEG and phase synchronization of EEG to localize epileptic sites from high density scalp EEG interictal recordings. Conference Proceedings of the International Conference of IEEE Engineering in Medicine and Biology Society, 2008, 4548-4550. doi: 10.1109/IEMBS.2008.4650224
Riley, M. A., Shockley, K., & Van Orden, G. (in press). Learning from the body about the mind. topiCS.
Riley, M. A., & Turvey, M. T. (2002). Variability and determinism in elementary behaviors. Journal of Motor Behavior, 34, 99-125. doi:10.1080/00222890209601934
Roberts, S., & Pashler, H. (2000). How persuasive is a good fit? A comment on theory testing. Psychological Review, 107, 358–367. doi:10.1037/0033-295X.107.2.358
Sackmann, E. (1995). Biological Membranes Architecture and Function. In: R. Lipowsky & E. Sackmann (eds.) Handbook of Biological Physics (pp. 4-62). Amsterdam: Elsevier.
Silberstein, M., & Chemero, A. (in press). Complexity and extended phenomenological–cognitive systems. topiCS.
Schmitt, D. T., & Ivanov, P. C. (2007). Fractal scale-invariant and nonlinear properties of cardiac dynamics remain stable with advanced age: a new mechanistic picture of cardiac control in healthy elderly. American Journal of Phsyiology: Regulatory integrative and Comparative Physiology, 293, R1923-R1937.
Schmitt, D. T., Stein, P. K., & Ivanov, P. C. (2009). Stratification pattern of static and scale-invariant dynamic measures of heartbeat fluctuations across sleep stages in young and elderly, IEEE Transactions on Biomedical Engineering, 56, 1564-1573.
Schumann, A. Y., Bartsch, R. P., Penzel, T., Ivanov, P. C., & Kantelhardt, J. W. (2010). Aging effects on cardiac and respiratory dynamics in healthy subjects across sleep stages. Sleep, 33, 943-955.
Slifkin, A. B., & Newell, K. M. (1998). Is variability in human performance a reflection of system noise? Current Directions in Psychological Science, 7, 170-177. doi:10.1111/1467-8721.ep10836906
Smith, T. G., Jr., Marks, W. B., Lange, G. D., Sheriff, W. H., Jr., & Neale, E. A. (1989). A fractal analysis of cell images. Journal of Neuroscience Methods, 27(2), 173–180.  doi:10.1016/0165-0270(89)90100-3
Soltys, Z., Ziaja, M., Pawlinski, R., Setkowicz, Z., & Janeczko, K. (2001). Morphology of reactive microglia in the injured cerebral cortex. Fractal analysis and complementary quan¬titative methods. Journal of Neuroscience Research, 63, 90–97. doi: 10.1002/1097-4547(20010101)63:1<90::AID-JNR11>3.0.CO;2-9
Spasic, S., Kesic, S., Kalauzi, A., & Saponjic, J. (2010). Different anesthesia in rat induces distinct inter-structure brain dynamic detected by Higuchi fractal dimension. Fractals, 19(1), 113-123. doi: 10.1142/S0218348X1100521X
Stergiou, N., & Decker, L. M. (2011). Human movement variability, nonlinear dynamics, and pathology: Is there a connection? Human Movement Science, 30, 869-888. doi:10.1016/j.humov.2011.06.002
Takeda, T., Sakata, A., & Matsuoka, T. (1999). Fractal dimensions in the occurrence of miniature end-plate potential in a vertebrate neuromuscular junction. Progress in Neuro-Psychopharmacology and Biological Psychiatry, 23(6), 1157–1169.  doi:10.1016/S0278-5846(99)00050-0
Thornton, T. L., & Gilden, D. L. (2005). Provenance of correlations in psychological data. Psychonomic Bulletin and Review, 12, 409–441. doi:10.3758/BF03193785
Tognoli, E., & Kelso, J. A. S. (2009). Brain coordination dynamics: True and false faces of phase synchrony and metastability. Progress in Neurobiology, 87(1), 31-40. doi:10.1016/j.pneurobio.2008.09.014
Torre, K. & Balasubramaniam, R. (2011). Disentangling stability, variability and adaptability in human performance: Focus on the interplay between local variance and serial correlation. Journal of Experimental Psychology: Human Perception and Performance, 37, 539-550. doi:10.1037/a0020556
Torre, K., & Delignières, D. (2008a). Unraveling the finding of 1/fb noise in self-paced and synchronized tapping: A unifying mechanistic model. Biological Cybernetics, 99, 159–170. doi:10.1007/s00422-008-0247-8
Torre, K. & Delignières, D. (2008b). Distinct ways for timing movements in bimanual coordination tasks: The contribution of serial correlation analysis and implications for modelling. Acta Psychologica, 129, 284-296. doi:10.1016/j.actpsy.2008.08.003
Torre, K., & Wagenmakers, E. J. (2009). Theories and models for 1/fb noise in human movement science. Human Movement Science, 28, 297–318. doi:10.1016/j.humov.2009.01.001
Valdez, A., & Amazeen, E. (2008). Using 1/f noise to examing planning and control in a discrete aiming task. Experimental Brain Research, 187, 303-319. doi:10.1007/s00221-008-1305-0
Vanderlei, L. C., Pastre, C. M., Jùnior, I. F. F., & de Godoy, M. F. (2010). Fractal correlation of heart rate variability in obese children. Autonomic Neuroscience: Basic and Clinical, 155, 125-129. doi:10.1016/j.autneu.2010.02.002
Van Orden, G., Holden, J. G., & Turvey, M. T. (2003). Self-organization of cognitive performance. Journal of Experimental Psychology: General, 132, 331-350. doi:10.1037/0096-3445.132.3.331
Van Orden, G., Holden, J. G., & Turvey, M. T. (2005). Human cognition and 1/f scaling. Journal of Experimental Psychology: General, 134, 117-123. doi:10.1037/0096-3445.134.1.117
Varanda, W. A., Liebovitch, L. S., Figueiroa, J. N., & Nogueira, R. A. (2000). Hurst analysis applies to the study of single calcium-activated potassium channel kinetics. Journal of Theoretical Biology, 206, 343–353. doi:10.1006/jtbi.2000.2131
Varela, F., Lachaux, J.-P., Rodriguez, E., & Martinerie, J. (2001). The Brainweb: phase synchronization and large scale integration. Nature Reviews Neuroscience, 2, 229–239. doi:10.1038/35067550
Ward, L. M. (2002). Dynamical cognitive science. Cambridge: MIT Press.
Ward, L. M., & Richard, C. M. (2001). 1/f noise and decision complexity. Unpublished manuscript, University of British Columbia.
Wagenmakers, E.-J., Farrell, S., & Ratcliff, R. (2004). Estimation and interpretation of 1/f α noise in human cognition. Psychonomic Bulletin & Review, 11, 579-615.
Wagenmakers, E.-J., Farrell, S., & Ratcliff, R. (2005). Human cognition and a pile of sand: A discussion on serial correlations and self-organized criticality. Journal of Experimental Psychology: General, 135, 108-116. doi:10.1037/0096-3445.134.1.108
Wagenmakers, E.-J., van der Maas, H. L. J., & Farrell, S. (in press). Abstract concepts require concrete models: Why cognitive scientists have not yet embraced nonlinearly-coupled, dynamical, self-organized critical, synergistic, scale-free, exquisitely context-sensitive, interaction-dominant, multifractal, interdependent brain-body-niche systems. topiCS.
Werner, G. (2007). Perspectives on the neuroscience of cognition and consciousness. Biosystems, 87(1), 82-95.  doi:10.1016/j.biosystems.2006.03.007
Werner, G. (2010). Fractals in the nervous system: conceptual implications for theoretical neuroscience. Frontiers in Fractal Physiology, 1, 1-28. doi:10.3389/fphys.2010.00015
West, B. J. (2006). Where Medicine Went Wrong. Singapore: World Scientific.
West, B. J. (2010). Fractal physiology and the fractional calculus: a perspective. Frontiers in Fractal Physiology, 1(12), 1-17. doi:10.3389/fphys.2010.00012
West, B. J., & Deering, W. (1994). Fractal physiology for physicists: levy statis¬tics. Physics Reports, 246, 1–100. doi:10.1016/0370-1573(94)00055-7
Wijnants, M. L., Bosman, A. M. T., Hasselman, F., Cox, R. F. A., & Van Orden, G. (2009). 1/f scaling in movement time changes with practice in precision aiming. Nonlinear Dynamics, Psychology, and Life Sciences, 13, 75-94. 
Wijnants, M. L., Cox, R. F. A., Hasselman, F., Bosman, A. M. T., & Van Orden, G. (2012). A trade-off study revealing nested timescales of constraint. Frontiers in Fractal Physiology, 3, 116. doi: 10.3389/fphys.2012.00116 
Wijnants, M. L., Hasselman, F., Cox, R. F. A., Bosman, A. M. T., & Van Orden, G. (2012). An interaction-dominant perspective on reading fluency and dyslexia. Annals of Dyslexia, 62, 100-119. doi: 10.1007/s11881-012-0067-3
Wing, A., Daffertshofer, A., & Pressing, J. (2004). Multiple time scales in serial production of force: A tutorial on power spectral analysis of motor variability. Human Movement Science, 23, 569-590. doi:10.1016/j.humov.2004.10.002
Wing, A. M., & Kristofferson, A. B. (1973). The timing of interresponse intervals. Perception and Psychophysics, 13, 455–460.
Yamamoto, N., Kubo, Y., Ishizawa, K., Kim, G., Moriya, T., Yamanouchi, T., Otsuka, K. (2010). Detrended fluctuation analysis is considered to be useful as a new indicator for short-term glucose complexity. Diabetes Technology and Therapeutics, 12, 775-783. doi:10.1089/dia.2010.0059
Yan, R., Yan, G., Zhang, W., & Wang, L. (2008). Long-range scaling behaviours in human colonic pressure activities. Communications in Nonlinear Science and Numerical Simulations, 13, 1888–1895. doi:10.1016/j.cnsns.2007.01.006
Zietsch, B., & Elston, G. N. (2005). Fractal analysis of pyramidal cells in the visual cortex of the Galago (Otolemur Garnetti): regional varia¬tion in dendritic branching patterns between visual areas. Fractals, 13, 83–90.
Zhang, L. (2006). Quantifying Brain White Matter Structural Changes in Normal Aging Using Fractal Dimension. Doctoral Thesis, Case Western Reserve University. http://etd.ohiolink.edu/send-pdf.cgi/Zhang%20Luduan.pdf?acc_num=case1126213038.


 
Footnotes

  Note that the scaling exponents in this four-response choice reaction task are somewhat reduced, compared with the findings of Kello et al., 2007. Note however, that these differences might be due to the fact that Ward & Richard fitted the spectral slope over all estimated frequencies, while Kello et al. (2007) only incorporated the lowest 25% of frequencies in their linear fit, as suggested by Eke, Hermàn, Kocsis, & Kozak (2002) and Holden (2005). All results in Figure 2 were obtained by fitting the spectral slope over the lowest 25% of frequencies only. 
Figures


 
Figure 1. Three different classes of temporal variability, white noise (a), 1/f scaling (c), and Brownian noise (e), and their respective power spectra are shown in the respective panels at the right.
 
 
Figure 2. The fractal scaling exponents from four independent experiments are shown. It is shown that 1/f scaling become more clearly present as the number of different response options decreases (see text). The shown tasks include word-naming, choice reaction, simple reaction, and precision aiming.
 
 
Figure 3. A schematic representation of the multi-scaled randomness construct. The left panel shows five hypothesized processes, each evolving at their own timescale. A time series composed of the sum of these processes may reveal 1/f-like noise in a power spectrum, which is shown in the right panel. Note that the processes are depicted schematically, and may compose random processes with differing relaxation times, rather than deterministic sine waves.
 
 
Figure 4. The top panel represents the plateaus induced by the discrete regime switches. The middle panel represents the autoregressive response variability that is inserted to the model. The response series shown in the lower panel was created by dividing the threshold criterion (top panel) by the information accrual time (middle panel), cf. Wagenmakers et al. (2004).
 
 

Figure 5. The top panel shows a white noise signal, which was added to the 1/f scaling in the lower left panel to construct the power spectrum in the right panel, which reveals fBmW noise, as indicated by the flattened slope at the highest frequencies, shown as a solid line. The dashed line represents the ideal 1/f scaling slope.

